name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: apt-impact-437902-g6
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build Docker image
      run: |
        docker build -t gcr.io/your-gcp-project-id/flask-app:latest .

    - name: Push Docker image to GCR
      run: |
        docker push gcr.io/your-gcp-project-id/flask-app:latest
